FROM eclipse-temurin:17

WORKDIR /NotSpring

COPY target/DecentralizedDatabaseNode-1.0-SNAPSHOT.jar /DecentralizedDatabaseNode/DecentralizedDatabaseNode-1.0-SNAPSHOT.jar

CMD ["java", "-jar", "/DecentralizedDatabaseNode/DecentralizedDatabaseNode-1.0-SNAPSHOT.jar"]